### ISSUE TITLE
Update site to Focus on Net Neutrality

### ISSUE THREAD

**Issue by ghost** [KeepOurNetFree/keepournetfree.github.io#116]
Update the info page to focus on net neutrality.

Some links to include:
https://act.credoaction.com/sign/Pai-netneutrality
https://www.fcc.gov/ecfs/filings/express

**Comment by dsuffern** [comment]
Want original content remain on the page, below new content or elsewhere?

**Comment by ghost** [comment]
Would probably be better if we kept the old content around, but if it becomes a UI sore we can just remove it.  Perhaps make the legacy content it's own page.

**Comment by dsuffern** [comment]
https://invis.io/YUBIZ56TS#/231652421_Screen_Shot_2017-05-02_At_12-44-01_AM
https://invis.io/YUBIZ56TS#/231652422_Screen_Shot_2017-05-02_At_12-44-28_AM

Quick view at updates I've got locally

**Comment by ghost** [comment]
This is some good shit!  The text itself needs some minor rewording.  But otherwise good shit!

**Comment by dsuffern** [comment]
I'm thinking about sharing major design updates like this through InvisionApp - people can leave feedback directly on the prototype, and I can share all the screen sizes - rather than just updating the code and relying on people checking it on their own local servers.. It's usually easier to manage feedback and progress with updates that way imo
